description = 'Shock is a Hugo theme for static sites.'

# PostCSS
[postCSS]
  state = false

# Header
[header]
  state = true
  brandLogo = false
  brandText = true
  fixedTop = true
  shadow = true

# Banner
[banner]
  home = true
  section = true
  single = false
  shadow = true

# Sidebar
[sidebar]
  home = false
  section = false
  single = false
  tableofcontentsID = 'sb-toc'

# Breadcrumbs
[breadcrumb]
  home = false
  homeIcon = 'folder-root'
  section = false
  single = false

# Heading
[heading]
  home = false
  section = false
  single = true
  description = false

# Footer
[footer]
  state = true
  stick = true
  shadow = true

# Connect
[connect]
  fediverse = ''

# Copyright
[copyright]
  name = ''
  link = ''
  year = ''

# Logo
[logo]
  mainPNG = 'img/logo/logo.png'
  brandPNG = 'img/logo/brand.png'

# Manifest
[manifest]
  state = true
  background = "#333"

# Robots
[robots]
  disallow = []
  llmsTXT = false
