name = 'shock'
license = 'MIT'
licenselink = 'https://codeberg.org/aao-fyi/shock/src/branch/main/LICENSE'
description = ''
homepage = 'https://codeberg.org/aao-fyi/shock'
tags = ['bootstrap', 'shock']
features = []
min_version = '0.128.0' # If changed, update hugo.toml

[author]
  name = 'aao.fyi'
  homepage = 'https://aao.fyi/'
