title = 'Shock'

# Info
baseURL = 'https://shock.aao.fyi/'
languageCode = 'en'
copyright = 'aao.fyi'

# Theme
theme = 'codeberg.org/aao-fyi/shock'

# Features
disableHugoGeneratorInject = true
disableKinds = []
enableGitInfo = true
enableRobotsTXT = true

# Minify
[minify]
  minifyOutput = true

# Build
[build]
  # PostCSS
  writeStats = true

# Module
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.146.0'

[menu]
  # Connect
  [[menu.connect]]
    identifier = 'codeberg'
    name = 'Codeberg'
    weight = '10'
    color = '#2185d0'
    url = 'https://codeberg.org/aao-fyi/shock'
  [[menu.connect]]
    identifier = 'github'
    name = 'GitHub'
    weight = '20'
    color = '#4078c0'
    url = 'https://github.com/aao-fyi/shock'
  [[menu.connect]]
    identifier = 'gitlab'
    name = 'GitLab'
    weight = '15'
    color = '#fc6d26'
    url = 'https://gitlab.com/aao-fyi/shock'
  # Footer
  [[menu.footer]]
    identifier = 'sitemap'
    name = 'Sitemap'
    weight = '10'
    url = '/sitemap.xml'
  [[menu.footer]]
    identifier = 'privacy'
    name = 'Privacy'
    weight = '90'
    url = 'https://aao.fyi/privacy/'
  [[menu.footer]]
    identifier = 'terms'
    name = 'Terms'
    weight = '90'
    url = 'https://aao.fyi/terms/'
