description = 'Shock is a Hugo theme for static sites.'

# Bootstrap
[bootstrap]
  javascript = true

# PostCSS
[postCSS]
  state = true

# Header
[header]
  state = true
  brandLogo = false
  brandText = true
  fixedTop = true

# Banner
[banner]
  home = true
  section = true
  single = false

# Sidebar
[sidebar]
  home = false
  section = false
  single = true
  tableofcontentsID = 'sidebar-tableofcontents'

# Breadcrumbs
[breadcrumb]
  home = true
  homeIcon = 'server-crash'
  section = true
  single = true

# Heading
[heading]
  home = false
  section = false
  single = true
  description = true

# Footer
[footer]
  state = true
  stick = true

# Connect
[connect]
  fediverse = ''

# Copyright
[copyright]
  name = ''
  link = ''
  year = ''

# Logo
[logo]
  mainPNG = 'img/logo/logo.png'
  brandPNG = 'img/logo/brand.png'

# Manifest
[manifest]
  state = true
  background = "#333"

# Robots
[robots]
  disallow = []
  llmsTXT = true
